repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0 # Use the latest Black version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3" # Use the latest Prettier version
    hooks:
      - id: prettier
        files: '(\.sh|\.fish|\.jsx?|\.tsx?)$'
