name: Push pipeline

on:
  push:
    branches: ["*"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    using: "node20"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
