on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 18.14
      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Install Percy
        run: npm install --save-dev @percy/cli

      - name: Percy Snapshot
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_SNAPSHOT_TIMEOUT: 120000 # 60 seconds timeout
        run: npx percy snapshot public/
